trigger:
- master

jobs:
- job: VCPKGbuild
  pool:
    vmImage: 'windows-2019'
  timeoutInMinutes: 240
  steps:
  - checkout: self
    submodules: recursive
  - task: CopyFiles@2
    inputs:
      targetFolder: '$(Build.StagingDirectory)\_'
  - script: |
      call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
      call initvcpkg.cmd
    displayName: Build ROS2.net dependencies
    workingDirectory: '$(Build.StagingDirectory)\_'
  - task: PublishBuildArtifacts@1
    inputs:
      pathtoPublish: c:\opt\vcpkg
      artifactName: 'ros2vcpkg'
    condition: always()
